import {LinearGradient} from "expo-linear-gradient";import {router} from "expo-router";import {useEffect,useState} from "react";import {Pressable,StyleSheet,Text,View} from "react-native";import {healthCheck} from "@/lib/api";import {useAppStore} from "@/store/useAppStore";
export default function Home(){const[checking,setChecking]=useState(false);const connected=useAppStore(s=>s.apiConnected);const setConnected=useAppStore(s=>s.setApiConnected);
 async function check(){setChecking(true);try{await healthCheck();setConnected(true)}catch{setConnected(false)}finally{setChecking(false)}}useEffect(()=>{void check()},[]);
 return <LinearGradient colors={["#08090C","#12161D","#070809"]} style={s.root}><View style={s.hero}><Text style={s.eyebrow}>X-GLASSES</Text><Text style={s.title}>See. Understand.{"\n"}Respond.</Text><Text style={s.sub}>A command-driven AI vision companion. Your camera stays live; AI only runs when you ask.</Text>
 <View style={s.status}><View style={[s.dot,{backgroundColor:connected?"#67F59A":"#FF6B6B"}]}/><View><Text style={s.st}>{checking?"Checking…":connected?"Backend connected":"Backend offline"}</Text><Text style={s.statusSub}>{connected?"Ready for vision commands":"Check Settings → API URL"}</Text></View></View></View>
 <Pressable onPress={()=>router.push("/camera")} style={s.primary}><Text style={s.primaryT}>Open Live Vision</Text><Text style={s.primaryS}>Live camera · voice/text command · best-frame analysis</Text></Pressable>
 <Pressable onPress={()=>router.push("/chat")} style={s.card}><Text style={s.bt}>Assistant Chat</Text><Text style={s.bs}>Separate chatbot with spoken replies</Text></Pressable>
 <View style={s.row}><Pressable onPress={()=>router.push("/people")} style={[s.card,s.half]}><Text style={s.bt}>People</Text><Text style={s.bs}>Face enrollment</Text></Pressable><Pressable onPress={()=>router.push("/settings")} style={[s.card,s.half]}><Text style={s.bt}>Settings</Text><Text style={s.bs}>Backend & session</Text></Pressable></View>
 <Pressable onPress={check}><Text style={s.refresh}>Test backend</Text></Pressable></LinearGradient>}
const s=StyleSheet.create({root:{flex:1,padding:20,paddingTop:65},hero:{marginBottom:16},eyebrow:{color:"#9DA3AE",fontSize:12,letterSpacing:4,fontWeight:"800"},title:{color:"#FFF",fontSize:42,lineHeight:45,fontWeight:"900",marginTop:12},sub:{color:"#A8AFBA",fontSize:15,lineHeight:23,marginVertical:18},status:{padding:14,borderRadius:18,backgroundColor:"rgba(255,255,255,.06)",marginBottom:2,flexDirection:"row",alignItems:"center",gap:12},dot:{width:9,height:9,borderRadius:5},st:{color:"#FFF",fontWeight:"800"},statusSub:{color:"#7F8792",fontSize:12,marginTop:3},primary:{padding:18,borderRadius:21,backgroundColor:"#FFF",marginBottom:10},primaryT:{color:"#090A0D",fontSize:19,fontWeight:"900"},primaryS:{color:"#515862",marginTop:5,lineHeight:19},card:{padding:17,borderRadius:20,backgroundColor:"rgba(255,255,255,.065)",borderWidth:1,borderColor:"rgba(255,255,255,.1)",marginBottom:10},bt:{color:"#FFF",fontSize:17,fontWeight:"800"},bs:{color:"#8E96A3",marginTop:5,lineHeight:19},row:{flexDirection:"row",gap:10},half:{flex:1},refresh:{color:"#FFF",fontWeight:"800",textAlign:"center",padding:12}});
